---
layout: post
title:  "Sesja społeczności R"
date:   2017-04-26
category: info
---

**Dla kogo ?** 

Dla wszystkich zaangażowanych w tworzenie społeczności R w Polsce.
Zarówno dla osób, które takie grupy prowadzą, jak również dla tych którzy chcą utworzyć społeczność entuzjastów R w swojej okolicy :) 

**Dlaczego ?**

Grupy pasjonatów odgrywają ogromną rolę w popularyzacji R. Celem każdego ze spotkań jest wymiana wiedzy i doświadczeń pomiędzy obecnymi i nowymi użytkownikami, kształcenie oraz networking. W Polsce aktywnie działa 6 grup. W trakcie sesji chcielibyśmy pomóc w znalezieniu inspiracji do dalszego działania oraz ułatwić wymianę doświadczeń związanych z organizacją społeczności skupiających entuzjastów R w Polsce. 

**Czego można się spodziewać ?**

Żywiołowej dyskusji pomiędzy przedstawicielami istniejących społeczności R w Polsce, pod kontrolą charyzmatycznego prowadzącego :)

# Chcesz wziąć aktywny udział w sesji?

Jeżeli jesteś zainteresowany/zainteresowana reprezentowaniem grupy do której należysz oraz aktywnym udziałem w sesji, pisz na nasz adres [whyr@mini.pw.edu.pl](mailto:whyr@mini.pw.edu.pl)

# Chcesz pomóc w organizacji?

Jeżeli jesteś zainteresowany/zainteresowana zaangażowaniem się w organizację **Why R? 2017**, pisz na nasz adres [whyr@mini.pw.edu.pl](mailto:whyr@mini.pw.edu.pl)


*Ania Rybińska* 